[supervisord]
nodaemon=true
logfile=/opt/rapax/logs/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=info

[unix_http_server]
file=/tmp/supervisor.sock

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:mariadb-exporter]
command=python3 /opt/rapax/bin/rapax-mariadb-data-exporterd.py
directory=/opt/rapax
autostart=true
autorestart=true
startretries=3
startsecs=10
stopwaitsecs=30
redirect_stderr=true
stdout_logfile=/opt/rapax/logs/mariadb-exporter.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
environment=RAPAXHOME="/opt/rapax",RAPAX_HOME="/opt/rapax",PYTHONPATH="/opt/rapax/lib"
