[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/opt/rapax/logs/supervisord.log
logfile_maxbytes=10MB
logfile_backups=3
loglevel=info

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:zabbix-data-processord]
command=/usr/local/bin/python3 /opt/rapax/bin/zabbix-data-processord.py
environment=RAPAXHOME="/opt/rapax",PYTHONPATH="/opt/rapax/lib",PYTHONUNBUFFERED="1"
directory=/opt/rapax
autostart=true
autorestart=true
startsecs=10
startretries=3
stopwaitsecs=10
stderr_logfile=/opt/rapax/logs/zabbix-data-processord.err.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3
stdout_logfile=/opt/rapax/logs/zabbix-data-processord.out.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
