[supervisord]
nodaemon=true
logfile=/opt/rapax/logs/supervisord.log
logfile_maxbytes=10MB
logfile_backups=5
loglevel=info
pidfile=/var/run/supervisord.pid
user=root

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:juniper-trap-processord]
command=/usr/local/bin/python3 /opt/rapax/bin/juniper-trap-processord.py --syslog-file %(ENV_SYSLOG_FILE)s --component-id %(ENV_COMPONENT_ID)s
directory=/opt/rapax
autostart=true
autorestart=true
startretries=10
startsecs=5
stopwaitsecs=10
stdout_logfile=/opt/rapax/logs/juniper-trap-processord-stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/opt/rapax/logs/juniper-trap-processord-stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3
environment=RAPAXHOME="/opt/rapax",PYTHONPATH="/opt/rapax/lib"
